### ISSUE TITLE
Launch Files not working in ROS2 Humble 

### ISSUE THREAD

**Issue by logansehr11** [DavidSegalle/p3dx_model_ros2#1]
A common issue using this port is the launch files are erroring out or are not working at all. This could be user error as no order of commands are provided launch the simulation correctly in the README and/or certain packages not being installed on Ubuntu, if this is the case could you provide me with the correct packages or commands to resolve this issue.

Example error:
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [launch]:
 - RuntimeError: Unrecognized entity of the type: param
 - SyntaxError: invalid syntax (p3dx.launch, line 1)

**Comment by DavidSegalle** [comment]
Aplogies!

This project was abandoned some time near when we decided to build our own custom robot base in real life and shifted focus. If you are interested in this base specifically the easiest solution seems to be abandon everything except the robot description and go from there. 

The approach of porting everything didn't work due to gazebo changes. I believe some files and plugins such as those related to diff_drive and LIDAR need to be altered. The error you find is due to ROS2 no longer supporting global parameters in launch files, the easy solution being just setting the params inside their respective node tags as necessary. 

I am currently not able to work on this project due to having my plate full and only ROS 1 noetic in my computer. I will, however, have some free days of vacation and if you need this robot model specifically I would be happy to work on it (maybe as a duo? And in ROS jazzy?). I believe the experience I got from a uni [https://github.com/ViDaProjects/aspirator3000.git](project) should help some.

If you're interested I would appreciate some contact info and a helping hand, otherwise just tell me and I will private this repo until I get some free time or interest

**Comment by logansehr11** [comment]
Hello, I appreciate you coming back to an old project to respond to concerns, I am in a similar situation to you where I also have a lot on my plate, so I am not looking to continue working on this and I apologize if my initial concerns may have made it seem that way.

Although this repository was not working entirely, it was a very helpful tool. I was using this repository as a reference to the robot I am building a simulation for and was just interested as to why .launch files may not be working opposed to the eventual successful .launch.py files I created. 

It may be helpful to keep it up for those working with similar robots that do not have a lot of ROS2 resources online, but it could just be that my project was very niche as I am working with a robot that is quite old.

Once again I thank you for coming back to reply to a thread on one of your old projects.
